name: Compilation & tests

on: [push, pull_request]

jobs:
  job_build_debug:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: docker://ledgerhq/ledger-app-builder:1.6.1-2

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build Compound plugin
        run: |
          make DEBUG=1

      - name: Upload Compound binary
        uses: actions/upload-artifact@v2
        with:
          name: compound-app-debug
          path: bin
